### ISSUE TITLE
兄弟密码泄露了长点心吧

### ISSUE THREAD

**Issue by jonntd** [sinxone/CTList#1]
兄弟密码泄露了长点心吧

**Comment by sinxone** [comment]
呃。&nbsp;尴尬了。&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jonn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月21日(星期二) 晚上11:21
收件人:&nbsp;"sinxone/CTList"<CTList@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[sinxone/CTList] 兄弟密码泄露了长点心吧 (#1)





 
兄弟密码泄露了长点心吧
